### ISSUE TITLE
Various meta shenanigans

### ISSUE THREAD

**Issue by SomeKittens** [SomeKittens/baddsert#12]
- [x] Travis Badge
- [x] npm badge/poster
- [x] greenkeeper
### Docs
- [ ] Mocha injection
- [ ] Better CLI examples
- [ ] `.baddrc` (when that's a thing)
- [ ] whatever else I think of
